### ISSUE TITLE
config in a single file

### ISSUE THREAD

**Issue by houdini-project** [guisanchez/DeFCon2#2]
Can you gather all the program configuration params in a single file (xml or json)?
Thanks in advance.

**Comment by guisanchez** [comment]
I did not find any fortran routine to read json files. For the moment I am working in a python script to load a json file and create the input files that my .f needs.

**Comment by B0RJA** [comment]
The python solution seems ok to me.
If still interested, there is a Fotran 95 JSON parser:
https://github.com/josephalevin/fson
and several XML parsers:
http://xml-fortran.sourceforge.net/

**Comment by guisanchez** [comment]
After the last update, the code works with a single config file (in json). The number of files has been reduced and the tree structure is more friendly.
Thanks for your suggestions.
