### ISSUE TITLE
test case

### ISSUE THREAD

**Issue by houdini-project** [guisanchez/DeFCon2#3]
Can you add all the necessary files to run a case to be able to test the program?
Thanks in advance.

**Comment by guisanchez** [comment]
In the project [page](http://guisanchez.github.com/2D-Debris/) you can download an input example. I will close this issue now. Nevertheless, if you need any other case do not hesitate to reopen it.
The project page is under construction. Thanks for your understanding. 
Thanks again for your suggestions.

**Comment by B0RJA** [comment]
Sorry to re-open the issue but,

can you add a config file to the test case?

Thanks in advance.

**Comment by guisanchez** [comment]
The download file you may find in the [web](http://guisanchez.github.com/2D-Debris/) contains a json input file. Hope it works. In addition, you can watch there a beautiful animation.
