### ISSUE TITLE
error with the test file

### ISSUE THREAD

**Issue by sumitpo** [guisanchez/DeFCon2#5]
I download the test file http://guisanchez.github.com/DeFCon2/mesh/case1.zip, and test the program with ./main2D input.js, and get following error: Unable to resolve path: friclaw, I read the source file, there is some wrong with the test file.

**Comment by jburguete** [comment]
The input.js file is outdated in this example
An updated input.js file has to be as

```
{
    "time" : 
    {
	"cfl": 0.9,
	"end": 30.0,
	"vtklag": 1.0,
	"stdprint": 10
    },
    "friclaw": "Voellmy",
    "params" : 
    {
	"tanphi": 0.1,
	"Xi": 0.02,
	"k": 1.0
    },
    "preproc_mesh": 0,
    "preproc_err": 1,
    "standard_out": 1,
    "compare_result": 0,
    "generate_vtk": 1,
    "mesh": "examplemesh1.txt",
    "h_initial": "exampleinitial1.txt",
    "stop" :
    {
	"stime" : 100.0,
	"Ekstop" : 10000.0
    }
}
```

**Comment by sumitpo** [comment]
Thank you! this works.

**Comment by B0RJA** [comment]
I have updated the file in the branch
